version: '3.7'

services:
  node-ts:
    image: postgres
    container_name: node-ts
    restart: always
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=ignite
    - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: node-ts
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
volumes:
  pgdata:
    driver: local
